### ISSUE TITLE
现在路线图上已经实现了哪些部分

### ISSUE THREAD

**Issue by wavemomo** [orcastor/orcas#2]
现在路线图上已经实现了哪些部分，在您提供的文档上并没有提及这些，方便整合一下吗

**Comment by orca-zhang** [comment]
> 现在路线图上已经实现了哪些部分，在您提供的文档上并没有提及这些，方便整合一下吗

@wavemomo 目前暂时实现了

1. ✅ 路线图第一部分最基础的文件读写（基于[command line工具](https://github.com/orcastor/orcas/blob/master/sdk/sdk_test.go)）
2. ✅ 路线图第二部分：
- [HTTP协议](https://github.com/orcastor/orcas/tree/master/rpc)，HTTP2.0/HTTP3.0（基于Caddy实现，详见[web-UI](https://github.com/orcastor/webapp)项目下的Caddyfile配置文件）
- [JWT鉴权](https://github.com/orcastor/orcas/blob/master/rpc/middleware/jwt.go)，[PBKDF2](https://github.com/orcastor/orcas/blob/master/core/core.go#L111)用户信息存储加密
- 基于[web-UI](https://github.com/orcastor/webapp)的基本的列举（目录list和文件对象get）
- 主要文档类型的[在线预览](https://github.com/orcastor/addon-previewer)等体验

> 前面一段时间主要忙于换工作，最近在同时申请NUS的Master of Technology in Intelligent Systems（准备材料、备考雅思等），短时间无法投入时间更新，感谢持续关注。
